---
- name: "print api_groups"
  debug:
    msg: "{{ api_groups }}"

- name: "print api"
  include_role:
      name: print-api
  vars:
      item: "{{ loop_item }}"
      # environment: "{{ loop_item.environment }}"
  loop: "{{ api_groups }}"
  loop_control: 
    loop_var: loop_item
  when: api_groups is defined and (api_groups | length > 0)
  