---
# test playbook
- name: example1
  hosts: localhost 
  vars:
    version_number: '2.4.37'
    # server: 'Ubuntu'
  gather_facts: false
  roles:
    - { role: generate-example-template }
    - { role: get-api-list }
